### ISSUE TITLE
make:models command not found

### ISSUE THREAD

**Issue by manzwebdesigns** [mrcorex/laravel-model-generator#3]
Hi,

I am trying to create models using the following command:

`php artisan make:models ehymns "authcomps,hymns,recordings,types,user_comments,users"`

it returns this error:
                                     
```
  [InvalidArgumentException]         
  Database [ehymns] not configured.
```  

so, I try it with the --env switch and I get this:

`php artisan make:models ehymns "authcomps,hymns,recordings,types,user_comments,users" --env`

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "make:models" is not defined.                           
  Did you mean one of these?                                      
      make:model                                                  
      make:auth                                                   
      make:command                                                
      make:controller                                             
      make:event                                                  
      make:job                                                    
      make:listener                                               
      make:mail                                                   
      make:middleware                                             
      make:notification                                           
      make:policy                                                 
      make:provider                                               
      make:request                                                
      make:seeder                                                 
      make:test                                                   
      make:migration 
```

the ehymns database exists as well as the tables.

`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

`php -v`
```
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

```
`config/corex.php`
```
<?php

return [
    'laravel-model-generator' => [
        'path' => base_path('app/Models'),
        'namespace' => 'App\Models',
        'databaseSubDirectory' => true
    ]
];
```
My Laravel version is 5.3.29

**Comment by mrcorex** [comment]
Hi there.

Make sure that the command has been registered. If you use following command "php artisan --env=local" you should see a long list of commands that are available in the local (develop) environment. If you cannot see "make:models" in this list, you need to register the command by added the required code to the "AppServiceProviders" in the method "register". You can see the required code in the readme.md file.

If you use the command "php artisan help make:models" you will see help for that command. I have to admit that it is a little misleading when it says ....

```
Arguments:
  database         Name of database.
  tables           Comma separated table names to generate. Specify "." to generate all.

```
.... because the argument "database" is actually the name of you connection pointing to that database.

It means, that if you have a database called "ehymns" and the default connection name is "mysql", your command would be ....
`php artisan make:models mysql "authcomps,hymns,recordings,types,user_comments,users"`

The switch "--env=local" is not needed if you already runs in the local environment.

Sorry for the confusion. If you do a "composer update" on this package, you will see it is now called "connection" and should work as intended.

**Comment by manzwebdesigns** [comment]
Thank you, that fixed it for me!
